import type { LessonPack } from '../types'

const home = {
  cadet: {
    'readme.txt': 'Welcome to Daedalus Terminal Academy.\nType help to begin.\n',
    notes: {
      'todo.txt': '1. learn pwd\n2. learn ls\n3. learn cd\n',
    },
    '.secret': 'classified: phosphor-green\n',
    logs: {
      'app.log': 'INFO start\nWARN disk\nINFO ok\nERROR boom\nINFO done\n',
      'access.log': 'GET /\nGET /api\nPOST /login\nGET /\n',
    },
    data: {
      'names.txt': 'zeta\nalpha\nbeta\nalpha\ngamma\n',
      'numbers.txt': '3\n1\n4\n1\n5\n',
    },
  },
}

export const fundamentalLessons: LessonPack[] = [
  {
    id: 'fund-pwd',
    title: 'Where am I?',
    track: 'fundamentals',
    order: 1,
    level: 'intro',
    startUnlocked: true,
    summary: 'Print the working directory with pwd.',
    prose: [
      'Every shell session has a current working directory — the folder you are “in”.',
      'The command pwd (print working directory) shows that absolute path.',
      'Run pwd, then press Check.',
    ],
    goals: [{ id: 'g1', label: 'Run pwd and show your location' }],
    hints: ['Type: pwd'],
    unlocks: ['fund-ls'],
    setup: {
      cwd: '/home/cadet',
      files: { home },
    },
    checks: [
      {
        type: 'lastCommandIs',
        command: 'pwd',
        message: 'Run the pwd command (exactly), then Check',
      },
      {
        type: 'stdoutEquals',
        text: '/home/cadet\n',
        message: 'pwd should print /home/cadet',
      },
      { type: 'lastExit', code: 0 },
    ],
  },
  {
    id: 'fund-ls',
    title: 'List files',
    track: 'fundamentals',
    order: 2,
    level: 'intro',
    summary: 'Use ls to see what is in a directory.',
    prose: [
      'ls lists names in the current directory.',
      'Try ls, then ls notes to look inside a subdirectory.',
      'For this check, list the contents of your home directory.',
    ],
    goals: [{ id: 'g1', label: 'List home with ls' }],
    hints: ['Type: ls'],
    unlocks: ['fund-cd'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'lastCommandMatches',
        pattern: '^ls(\\s|$)',
        message: 'Run ls (optionally with flags/paths), then Check',
      },
      { type: 'stdoutContains', text: 'readme.txt', message: 'Run ls in /home/cadet so readme.txt appears' },
      { type: 'lastExit', code: 0 },
    ],
  },
  {
    id: 'fund-cd',
    title: 'Change directory',
    track: 'fundamentals',
    order: 3,
    level: 'intro',
    summary: 'Move into notes/ with cd.',
    prose: [
      'cd path changes the working directory.',
      'cd .. goes up one level. cd ~ (or cd with no args) returns home.',
      'Navigate into the notes directory.',
    ],
    goals: [{ id: 'g1', label: 'cd into ~/notes' }],
    hints: ['cd notes', 'Then Check — cwd must be /home/cadet/notes'],
    unlocks: ['fund-cat'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [{ type: 'cwdIs', path: '/home/cadet/notes' }],
  },
  {
    id: 'fund-cat',
    title: 'Read a file',
    track: 'fundamentals',
    order: 4,
    level: 'intro',
    summary: 'Print a file with cat.',
    prose: [
      'cat file writes the file contents to the terminal.',
      'Read todo.txt inside notes/.',
    ],
    goals: [{ id: 'g1', label: 'cat notes/todo.txt (from home or inside notes)' }],
    hints: ['From home: cat notes/todo.txt'],
    unlocks: ['fund-hidden'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'lastCommandMatches',
        pattern: '^cat\\s+',
        message: 'Use cat to read the file, then Check',
      },
      {
        type: 'stdoutContains',
        text: 'learn pwd',
        message: 'cat the todo file so its text appears in stdout',
      },
      { type: 'lastExit', code: 0 },
    ],
  },
  {
    id: 'fund-hidden',
    title: 'List hidden files',
    track: 'fundamentals',
    order: 5,
    level: 'intro',
    summary: 'Reveal dotfiles with ls -a.',
    prose: [
      'Names starting with . are hidden from plain ls.',
      'ls -a shows them. There is a .secret file in your home — find it.',
    ],
    goals: [{ id: 'g1', label: 'ls -a and show .secret' }],
    hints: ['ls -a'],
    unlocks: ['fund-mkdir-mv'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'lastCommandMatches',
        pattern: '^ls\\s+-[a-zA-Z]*a',
        message: 'Run ls with -a (e.g. ls -a or ls -la), then Check',
      },
      { type: 'stdoutContains', text: '.secret', message: 'Use ls -a so .secret is listed' },
      { type: 'lastExit', code: 0 },
    ],
  },
  {
    id: 'fund-mkdir-mv',
    title: 'Make a directory and move a file',
    track: 'fundamentals',
    order: 6,
    level: 'core',
    summary: 'mkdir archive, then mv readme.txt into it.',
    prose: [
      'mkdir creates a directory. mv renames or moves files.',
      'Create archive/ in your home, then move readme.txt into it.',
    ],
    goals: [
      { id: 'g1', label: 'Create ~/archive' },
      { id: 'g2', label: 'Move readme.txt into archive/' },
    ],
    hints: ['mkdir archive', 'mv readme.txt archive/'],
    unlocks: ['fund-echo-redir'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      { type: 'fileExists', path: '/home/cadet/archive' },
      {
        type: 'fileExists',
        path: '/home/cadet/archive/readme.txt',
        message: 'readme.txt should live under archive/',
      },
      { type: 'fileMissing', path: '/home/cadet/readme.txt' },
    ],
  },
  {
    id: 'fund-echo-redir',
    title: 'Write with echo and >',
    track: 'fundamentals',
    order: 7,
    level: 'core',
    summary: 'Create hello.txt using echo and a redirect.',
    prose: [
      'echo prints text. The > operator writes command output into a file (overwrite).',
      'Create hello.txt containing exactly: hello daedalus',
    ],
    goals: [{ id: 'g1', label: 'Write hello.txt via redirect' }],
    hints: ['echo hello daedalus > hello.txt'],
    unlocks: ['fund-append'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'fileEquals',
        path: '/home/cadet/hello.txt',
        content: 'hello daedalus\n',
      },
    ],
  },
  {
    id: 'fund-append',
    title: 'Append with >>',
    track: 'fundamentals',
    order: 8,
    level: 'core',
    summary: 'Append a second line with >>.',
    prose: [
      '>> appends instead of overwriting.',
      'Start from hello.txt that already says hello. Append the line: more text',
    ],
    goals: [{ id: 'g1', label: 'Append to hello.txt' }],
    hints: ['echo more text >> hello.txt'],
    unlocks: ['fund-pipe-grep'],
    setup: {
      cwd: '/home/cadet',
      files: {
        home: {
          cadet: {
            'hello.txt': 'hello\n',
          },
        },
      },
    },
    checks: [
      {
        type: 'fileEquals',
        path: '/home/cadet/hello.txt',
        content: 'hello\nmore text\n',
      },
    ],
  },
  {
    id: 'fund-pipe-grep',
    title: 'Pipes and grep',
    track: 'fundamentals',
    order: 9,
    level: 'core',
    summary: 'Filter log lines with cat | grep.',
    prose: [
      'A pipe | sends stdout of one command to stdin of the next.',
      'From home, filter ERROR lines out of logs/app.log.',
    ],
    goals: [{ id: 'g1', label: 'Show ERROR lines from app.log' }],
    hints: ['cat logs/app.log | grep ERROR', 'Or: grep ERROR logs/app.log'],
    unlocks: ['fund-wc'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      { type: 'stdoutContains', text: 'ERROR boom' },
      {
        type: 'stdoutEquals',
        text: 'ERROR boom\n',
        message: 'Stdout should be only the ERROR line',
      },
    ],
  },
  {
    id: 'fund-wc',
    title: 'Count lines with wc',
    track: 'fundamentals',
    order: 10,
    level: 'core',
    summary: 'Use wc -l on a log file.',
    prose: [
      'wc counts lines (-l), words (-w), and bytes (-c).',
      'How many lines are in logs/access.log? Print just the count.',
    ],
    goals: [{ id: 'g1', label: 'wc -l logs/access.log' }],
    hints: ['wc -l logs/access.log'],
    unlocks: ['fund-sort-uniq'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'stdoutContains',
        text: '4',
        message: 'access.log has 4 lines — use wc -l',
      },
    ],
  },
  {
    id: 'fund-sort-uniq',
    title: 'sort and uniq',
    track: 'fundamentals',
    order: 11,
    level: 'core',
    summary: 'Sort names and collapse duplicates.',
    prose: [
      'sort orders lines. uniq removes adjacent duplicates (so sort first).',
      'Produce the unique sorted names from data/names.txt.',
    ],
    goals: [{ id: 'g1', label: 'sort data/names.txt | uniq' }],
    hints: ['sort data/names.txt | uniq'],
    unlocks: ['fund-head-tail'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'stdoutEquals',
        text: 'alpha\nbeta\ngamma\nzeta\n',
      },
    ],
  },
  {
    id: 'fund-head-tail',
    title: 'head and tail',
    track: 'fundamentals',
    order: 12,
    level: 'core',
    summary: 'Read the ends of a file.',
    prose: [
      'head shows the first lines; tail shows the last.',
      'Print the last 2 lines of logs/app.log.',
    ],
    goals: [{ id: 'g1', label: 'tail -n 2 logs/app.log' }],
    hints: ['tail -n 2 logs/app.log'],
    unlocks: ['fund-chmod'],
    setup: { cwd: '/home/cadet', files: { home } },
    checks: [
      {
        type: 'stdoutEquals',
        text: 'ERROR boom\nINFO done\n',
      },
    ],
  },
  {
    id: 'fund-chmod',
    title: 'Permissions with chmod',
    track: 'fundamentals',
    order: 13,
    level: 'advanced',
    summary: 'Make a script executable (755).',
    prose: [
      'chmod MODE file sets permission bits. 755 means rwxr-xr-x.',
      'There is a tool.sh in your home. Make it mode 755.',
      'Confirm with ls -l if you like, then Check.',
    ],
    goals: [{ id: 'g1', label: 'chmod 755 tool.sh' }],
    hints: ['chmod 755 tool.sh', 'ls -l tool.sh'],
    unlocks: ['fund-ps-kill'],
    setup: {
      cwd: '/home/cadet',
      files: {
        home: {
          cadet: {
            'tool.sh': '#!/bin/sh\necho ready\n',
          },
        },
      },
    },
    checks: [{ type: 'modeIs', path: '/home/cadet/tool.sh', mode: '755' }],
  },
  {
    id: 'fund-ps-kill',
    title: 'Processes: ps and kill',
    track: 'fundamentals',
    order: 14,
    level: 'advanced',
    summary: 'List fake processes and stop one.',
    prose: [
      'This academy simulates a tiny process table.',
      'Use ps to inspect it, then kill the rogue worker (pid 4242).',
    ],
    goals: [{ id: 'g1', label: 'Stop pid 4242' }],
    hints: ['ps', 'kill 4242'],
    unlocks: ['jq-identity'],
    setup: {
      cwd: '/home/cadet',
      files: { home: { cadet: { 'readme.txt': 'ops desk\n' } } },
      processes: [
        { pid: 1, name: 'init', status: 'running' },
        { pid: 4242, name: 'rogue-worker', status: 'running' },
        { pid: 7, name: 'sshd', status: 'running' },
      ],
    },
    checks: [{ type: 'processStopped', pid: 4242 }],
  },
]
